// Migration script to populate firms data from static data
import { db } from "./db";
import { firmsData } from "./shared/schema";
import { eq } from "drizzle-orm";

const staticFirmsData = [
  {
    firmName: "Bank of America",
    headquarters: "Charlotte",
    ceo: "Brian Moynihan",
    totalDeals: 3245,
    totalValue: "£8,234.50 B",
    avgDealSize: "£2.54 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£8,234.50B",
    metric2Label: "Deals Completed",
    metric2Value: "3,245",
    metric3Label: "M&A Ranking",
    metric3Value: "#2",
    metric4Label: "Deal Success Rate",
    metric4Value: "92%",
    completedDealTitle: "Infrastructure Acquisition",
    completedDealDescription: "Advisory on £4.2B infrastructure acquisition in utilities sector",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Healthcare Merger",
    inProgressDealDescription: "Lead advisor on £2.8B healthcare sector merger",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Barclays",
    headquarters: "London",
    ceo: "C.S. Venkatakrishnan",
    totalDeals: 1856,
    totalValue: "£4,492.70 B",
    avgDealSize: "£2.42 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,492.70B",
    metric2Label: "Deals Completed",
    metric2Value: "1,856",
    metric3Label: "M&A Ranking",
    metric3Value: "#8",
    metric4Label: "Deal Success Rate",
    metric4Value: "87%",
    completedDealTitle: "Fintech Acquisition",
    completedDealDescription: "Advisory on £1.8B fintech acquisition in payments sector",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Real Estate Deal",
    inProgressDealDescription: "Lead advisor on £3.1B real estate transaction",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "BlackRock",
    headquarters: "New York",
    ceo: "Larry Fink",
    totalDeals: 892,
    totalValue: "£8,947.30 B",
    avgDealSize: "£10.03 B",
    metric1Label: "Assets Under Management",
    metric1Value: "£8,947.30B",
    metric2Label: "Deals Completed",
    metric2Value: "892",
    metric3Label: "Asset Management Ranking",
    metric3Value: "#1",
    metric4Label: "Client Satisfaction",
    metric4Value: "96%",
    completedDealTitle: "ESG Fund Launch",
    completedDealDescription: "Launch of £5.2B sustainable investment fund",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Infrastructure Fund",
    inProgressDealDescription: "Developing £4.7B infrastructure investment fund",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Blackstone",
    headquarters: "New York",
    ceo: "Steve Schwarzman",
    totalDeals: 1987,
    totalValue: "£7,234.80 B",
    avgDealSize: "£4.17 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£7,234.80B",
    metric2Label: "Deals Completed",
    metric2Value: "1,987",
    metric3Label: "Private Equity Ranking",
    metric3Value: "#1",
    metric4Label: "Portfolio Performance",
    metric4Value: "94%",
    completedDealTitle: "Technology Buyout",
    completedDealDescription: "£6.8B leveraged buyout of enterprise software company",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Logistics Acquisition",
    inProgressDealDescription: "£3.4B acquisition in logistics and supply chain",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Citi",
    headquarters: "New York",
    ceo: "Jane Fraser",
    totalDeals: 3421,
    totalValue: "£7,623.80 B",
    avgDealSize: "£2.23 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£7,623.80B",
    metric2Label: "Deals Completed",
    metric2Value: "3,421",
    metric3Label: "Global Banking Ranking",
    metric3Value: "#3",
    metric4Label: "Deal Success Rate",
    metric4Value: "91%",
    completedDealTitle: "Cross-Border M&A",
    completedDealDescription: "Advisory on £4.1B cross-border merger in financial services",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Energy Transition",
    inProgressDealDescription: "£2.9B financing for renewable energy projects",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Deutsche Bank",
    headquarters: "Frankfurt",
    ceo: "Christian Sewing",
    totalDeals: 1234,
    totalValue: "£3,456.70 B",
    avgDealSize: "£2.80 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£3,456.70B",
    metric2Label: "Deals Completed",
    metric2Value: "1,234",
    metric3Label: "European Banking Ranking",
    metric3Value: "#4",
    metric4Label: "Deal Success Rate",
    metric4Value: "88%",
    completedDealTitle: "Industrial Merger",
    completedDealDescription: "Advisory on £2.7B industrial conglomerate merger",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Automotive Deal",
    inProgressDealDescription: "£1.9B automotive sector transaction",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Evercore",
    headquarters: "New York",
    ceo: "John Weinberg",
    totalDeals: 876,
    totalValue: "£4,567.20 B",
    avgDealSize: "£5.21 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,567.20B",
    metric2Label: "Deals Completed",
    metric2Value: "876",
    metric3Label: "Boutique Banking Ranking",
    metric3Value: "#1",
    metric4Label: "Client Retention",
    metric4Value: "97%",
    completedDealTitle: "Healthcare M&A",
    completedDealDescription: "Advisory on £3.8B healthcare services merger",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "TMT Deal",
    inProgressDealDescription: "£2.6B technology, media & telecom transaction",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Goldman Sachs",
    headquarters: "New York",
    ceo: "David Solomon",
    totalDeals: 2134,
    totalValue: "£9,876.50 B",
    avgDealSize: "£4.63 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£9,876.50B",
    metric2Label: "Deals Completed",
    metric2Value: "2,134",
    metric3Label: "M&A Ranking",
    metric3Value: "#1",
    metric4Label: "Deal Success Rate",
    metric4Value: "95%",
    completedDealTitle: "Tech Acquisition",
    completedDealDescription: "Advisory on £7.2B technology acquisition in AI sector",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Energy Merger",
    inProgressDealDescription: "Lead advisor on £5.8B energy sector merger",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "HSBC",
    headquarters: "London",
    ceo: "Noel Quinn",
    totalDeals: 1678,
    totalValue: "£5,432.10 B",
    avgDealSize: "£3.24 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£5,432.10B",
    metric2Label: "Deals Completed",
    metric2Value: "1,678",
    metric3Label: "Asia Pacific Ranking",
    metric3Value: "#1",
    metric4Label: "Deal Success Rate",
    metric4Value: "89%",
    completedDealTitle: "Infrastructure Project",
    completedDealDescription: "Advisory on £3.7B infrastructure development in Asia",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Trade Finance Deal",
    inProgressDealDescription: "£2.4B trade finance facility for emerging markets",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "J.P.Morgan",
    headquarters: "New York",
    ceo: "Jamie Dimon",
    totalDeals: 4321,
    totalValue: "£12,345.60 B",
    avgDealSize: "£2.86 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£12,345.60B",
    metric2Label: "Deals Completed",
    metric2Value: "4,321",
    metric3Label: "Global Banking Ranking",
    metric3Value: "#1",
    metric4Label: "Deal Success Rate",
    metric4Value: "94%",
    completedDealTitle: "Mega Merger",
    completedDealDescription: "Advisory on £8.9B cross-industry mega merger",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Digital Transformation",
    inProgressDealDescription: "£4.2B digital transformation acquisition",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Jefferies",
    headquarters: "New York",
    ceo: "Rich Handler",
    totalDeals: 1098,
    totalValue: "£3,210.40 B",
    avgDealSize: "£2.92 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£3,210.40B",
    metric2Label: "Deals Completed",
    metric2Value: "1,098",
    metric3Label: "Mid-Market Ranking",
    metric3Value: "#2",
    metric4Label: "Client Satisfaction",
    metric4Value: "93%",
    completedDealTitle: "Mid-Cap Acquisition",
    completedDealDescription: "Advisory on £1.8B mid-market technology acquisition",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Growth Capital",
    inProgressDealDescription: "£1.4B growth capital transaction",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "KKR",
    headquarters: "New York",
    ceo: "Henry Kravis",
    totalDeals: 765,
    totalValue: "£6,789.30 B",
    avgDealSize: "£8.87 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£6,789.30B",
    metric2Label: "Deals Completed",
    metric2Value: "765",
    metric3Label: "Private Equity Ranking",
    metric3Value: "#2",
    metric4Label: "Portfolio IRR",
    metric4Value: "18.2%",
    completedDealTitle: "LBO Transaction",
    completedDealDescription: "£5.1B leveraged buyout in consumer goods sector",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Infrastructure Investment",
    inProgressDealDescription: "£3.8B infrastructure equity investment",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Lazard",
    headquarters: "New York",
    ceo: "Kenneth Jacobs",
    totalDeals: 987,
    totalValue: "£4,321.70 B",
    avgDealSize: "£4.38 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,321.70B",
    metric2Label: "Deals Completed",
    metric2Value: "987",
    metric3Label: "Advisory Ranking",
    metric3Value: "#3",
    metric4Label: "Deal Completion Rate",
    metric4Value: "96%",
    completedDealTitle: "Strategic Advisory",
    completedDealDescription: "Strategic advisory on £3.2B cross-border transaction",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Restructuring Deal",
    inProgressDealDescription: "£2.1B corporate restructuring advisory",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Morgan Stanley",
    headquarters: "New York",
    ceo: "James Gorman",
    totalDeals: 2987,
    totalValue: "£8,765.40 B",
    avgDealSize: "£2.93 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£8,765.40B",
    metric2Label: "Deals Completed",
    metric2Value: "2,987",
    metric3Label: "M&A Ranking",
    metric3Value: "#2",
    metric4Label: "Deal Success Rate",
    metric4Value: "93%",
    completedDealTitle: "Financial Services M&A",
    completedDealDescription: "Advisory on £6.1B financial services merger",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "SPAC Transaction",
    inProgressDealDescription: "£2.7B SPAC merger in cleantech sector",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "RBC Capital Markets",
    headquarters: "Toronto",
    ceo: "Doug McGregor",
    totalDeals: 1345,
    totalValue: "£4,567.80 B",
    avgDealSize: "£3.39 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,567.80B",
    metric2Label: "Deals Completed",
    metric2Value: "1,345",
    metric3Label: "Canadian Banking Ranking",
    metric3Value: "#1",
    metric4Label: "Deal Success Rate",
    metric4Value: "90%",
    completedDealTitle: "Natural Resources Deal",
    completedDealDescription: "Advisory on £2.9B natural resources transaction",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Mining Acquisition",
    inProgressDealDescription: "£2.1B mining sector acquisition",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Rothschild & Co",
    headquarters: "London",
    ceo: "Alexandre de Rothschild",
    totalDeals: 2156,
    totalValue: "£5,891.40 B",
    avgDealSize: "£2.73 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£5,891.40B",
    metric2Label: "Deals Completed",
    metric2Value: "2,156",
    metric3Label: "European Advisory Ranking",
    metric3Value: "#2",
    metric4Label: "Client Retention",
    metric4Value: "98%",
    completedDealTitle: "Family Business Sale",
    completedDealDescription: "Advisory on £3.4B family business divestiture",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Succession Planning",
    inProgressDealDescription: "£1.8B succession planning transaction",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "UBS",
    headquarters: "Zurich",
    ceo: "Sergio Ermotti",
    totalDeals: 2847,
    totalValue: "£6,345.60 B",
    avgDealSize: "£2.23 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£6,345.60B",
    metric2Label: "Deals Completed",
    metric2Value: "2,847",
    metric3Label: "Wealth Management Ranking",
    metric3Value: "#1",
    metric4Label: "Deal Success Rate",
    metric4Value: "91%",
    completedDealTitle: "Wealth Management M&A",
    completedDealDescription: "Advisory on £4.2B wealth management acquisition",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Swiss Banking Deal",
    inProgressDealDescription: "£2.8B Swiss private banking transaction",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Wells Fargo",
    headquarters: "San Francisco",
    ceo: "Charlie Scharf",
    totalDeals: 1456,
    totalValue: "£3,892.70 B",
    avgDealSize: "£2.67 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£3,892.70B",
    metric2Label: "Deals Completed",
    metric2Value: "1,456",
    metric3Label: "US Banking Ranking",
    metric3Value: "#4",
    metric4Label: "Deal Success Rate",
    metric4Value: "88%",
    completedDealTitle: "Regional Bank M&A",
    completedDealDescription: "Advisory on £2.3B regional bank merger",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Commercial Real Estate",
    inProgressDealDescription: "£1.7B commercial real estate financing",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Bain Capital",
    headquarters: "Boston",
    ceo: "John Connaughton",
    totalDeals: 456,
    totalValue: "£3,247.80 B",
    avgDealSize: "£7.12 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$185B",
    metric2Label: "Portfolio Companies",
    metric2Value: "450+",
    metric3Label: "PE Ranking",
    metric3Value: "#4",
    metric4Label: "IRR",
    metric4Value: "15.2%",
    completedDealTitle: "Healthcare Technology Buyout",
    completedDealDescription: "£8.5B acquisition of leading healthcare technology platform",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Software LBO",
    inProgressDealDescription: "£12.3B leveraged buyout in enterprise software sector",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Carlyle",
    headquarters: "Washington, D.C.",
    ceo: "Harvey Schwartz",
    totalDeals: 523,
    totalValue: "£4,156.90 B",
    avgDealSize: "£7.95 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$373B",
    metric2Label: "Portfolio Companies",
    metric2Value: "400+",
    metric3Label: "PE Ranking",
    metric3Value: "#2",
    metric4Label: "IRR",
    metric4Value: "14.8%",
    completedDealTitle: "Infrastructure Fund Deployment",
    completedDealDescription: "£15.2B deployment across renewable energy and digital infrastructure",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Real Estate Platform",
    inProgressDealDescription: "£9.8B acquisition of commercial real estate platform",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "CVC Capital Partners",
    headquarters: "London",
    ceo: "Rob Lucas",
    totalDeals: 387,
    totalValue: "£2,891.40 B",
    avgDealSize: "£7.47 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$186B",
    metric2Label: "Portfolio Companies",
    metric2Value: "350+",
    metric3Label: "PE Ranking",
    metric3Value: "#5",
    metric4Label: "IRR",
    metric4Value: "13.9%",
    completedDealTitle: "European Buyout Fund",
    completedDealDescription: "£11.4B European buyout focused on consumer and business services",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Technology Growth Investment",
    inProgressDealDescription: "£6.8B growth investment in European technology companies",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Apollo Global Management",
    headquarters: "New York",
    ceo: "Marc Rowan",
    totalDeals: 612,
    totalValue: "£5,234.80 B",
    avgDealSize: "£8.55 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$598B",
    metric2Label: "Portfolio Companies",
    metric2Value: "500+",
    metric3Label: "PE Ranking",
    metric3Value: "#1",
    metric4Label: "IRR",
    metric4Value: "16.1%",
    completedDealTitle: "Credit Strategies Deployment",
    completedDealDescription: "£18.7B deployment across credit strategies and opportunistic investments",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Healthcare Services Platform",
    inProgressDealDescription: "£13.2B acquisition of leading healthcare services platform",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "EQT Group",
    headquarters: "Stockholm",
    ceo: "Christian Sinding",
    totalDeals: 289,
    totalValue: "£1,214.20 B",
    avgDealSize: "£4.20 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$98B",
    metric2Label: "Portfolio Companies",
    metric2Value: "200+",
    metric3Label: "PE Ranking",
    metric3Value: "#7",
    metric4Label: "IRR",
    metric4Value: "12.7%",
    completedDealTitle: "Sustainable Investment Fund",
    completedDealDescription: "£8.3B deployment focused on sustainable infrastructure and tech",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Nordic Growth Platform",
    inProgressDealDescription: "£5.6B acquisition of Nordic technology growth platform",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Brookfield Asset Management",
    headquarters: "Toronto",
    ceo: "Bruce Flatt",
    totalDeals: 743,
    totalValue: "£9,512.40 B",
    avgDealSize: "£12.80 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$850B",
    metric2Label: "Portfolio Companies",
    metric2Value: "600+",
    metric3Label: "Infrastructure Ranking",
    metric3Value: "#1",
    metric4Label: "IRR",
    metric4Value: "14.2%",
    completedDealTitle: "Renewable Energy Portfolio",
    completedDealDescription: "£23.4B acquisition of global renewable energy infrastructure",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Real Estate Platform",
    inProgressDealDescription: "£16.7B expansion of commercial real estate portfolio",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Ares Management Corporation",
    headquarters: "Los Angeles",
    ceo: "Michael Arougheti",
    totalDeals: 456,
    totalValue: "£3,100.80 B",
    avgDealSize: "£6.80 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$378B",
    metric2Label: "Portfolio Companies",
    metric2Value: "380+",
    metric3Label: "Credit Ranking",
    metric3Value: "#3",
    metric4Label: "IRR",
    metric4Value: "13.5%",
    completedDealTitle: "Credit Strategies Expansion",
    completedDealDescription: "£12.6B deployment across direct lending and special situations",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Industrial Real Estate",
    inProgressDealDescription: "£8.4B acquisition of industrial real estate portfolio",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Oaktree Capital Management",
    headquarters: "Los Angeles",
    ceo: "Jay Wintrob",
    totalDeals: 324,
    totalValue: "£1,749.60 B",
    avgDealSize: "£5.40 B",
    metric1Label: "Total AUM (2024)",
    metric1Value: "$192B",
    metric2Label: "Portfolio Companies",
    metric2Value: "280+",
    metric3Label: "Distressed Ranking",
    metric3Value: "#1",
    metric4Label: "IRR",
    metric4Value: "15.8%",
    completedDealTitle: "Distressed Debt Fund",
    completedDealDescription: "£9.7B deployment in distressed debt and special situations",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "European Opportunities",
    inProgressDealDescription: "£6.2B European distressed opportunities fund",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Centerview Partners",
    headquarters: "New York",
    ceo: "Blair Effron",
    totalDeals: 234,
    totalValue: "£2,847.90 B",
    avgDealSize: "£12.17 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£2,847.90B",
    metric2Label: "Deals Completed",
    metric2Value: "234",
    metric3Label: "Boutique Advisory Ranking",
    metric3Value: "#1",
    metric4Label: "Average Deal Size",
    metric4Value: "£12.17B",
    completedDealTitle: "Large Cap M&A",
    completedDealDescription: "Advisory on £18.5B strategic merger in technology sector",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Mega Deal Advisory",
    inProgressDealDescription: "£22.3B cross-border acquisition advisory",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "PJT Partners",
    headquarters: "New York", 
    ceo: "Paul Taubman",
    totalDeals: 187,
    totalValue: "£1,923.40 B",
    avgDealSize: "£10.29 B",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£1,923.40B",
    metric2Label: "Deals Completed",
    metric2Value: "187",
    metric3Label: "Strategic Advisory Ranking",
    metric3Value: "#2",
    metric4Label: "Client Retention Rate",
    metric4Value: "96%",
    completedDealTitle: "Strategic Restructuring",
    completedDealDescription: "Advisory on £14.2B corporate restructuring and spin-off",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Defense Sector M&A",
    inProgressDealDescription: "£8.7B defense industry consolidation advisory",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "General Atlantic",
    headquarters: "New York",
    ceo: "Bill Ford",
    totalDeals: 456,
    totalValue: "£3,847.20 B",
    avgDealSize: "£8.43 B",
    firmType: "Fund",
    website: "generalatlantic.com",
    founded: "1980",
    employees: "800+",
    aum: "£75 B",
    companySummary: "General Atlantic is a leading global growth equity firm that provides capital and strategic support for growth companies. Founded in 1980, the firm combines a collaborative global approach, sector specific expertise, a long-term investment horizon and a deep understanding of growth drivers to partner with great entrepreneurs and management teams to scale innovative businesses around the world.",
    metric1Label: "Total Investments (2024)",
    metric1Value: "£3,847.20B",
    metric2Label: "Portfolio Companies",
    metric2Value: "456",
    metric3Label: "Growth Equity Ranking",
    metric3Value: "#1",
    metric4Label: "Portfolio Success Rate",
    metric4Value: "89%",
    completedDealTitle: "SaaS Platform Investment",
    completedDealDescription: "£850M growth investment in enterprise software platform",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Fintech Expansion",
    inProgressDealDescription: "£1.2B investment to support global fintech expansion",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Thoma Bravo",
    headquarters: "Chicago",
    ceo: "Orlando Bravo",
    totalDeals: 387,
    totalValue: "£4,234.60 B",
    avgDealSize: "£10.94 B",
    firmType: "Fund",
    website: "thomabravo.com",
    founded: "2008",
    employees: "500+",
    aum: "£130 B",
    companySummary: "Thoma Bravo is one of the largest software-focused private equity firms in the world. We are a hands-on investor with deep sector expertise and a proven track record of accelerating growth and creating value for our portfolio companies. Our strategic approach combines our operational resources, sector knowledge and capital to help software companies reach their full potential.",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,234.60B",
    metric2Label: "Software Deals",
    metric2Value: "387",
    metric3Label: "Software PE Ranking",
    metric3Value: "#1",
    metric4Label: "Portfolio Growth Rate",
    metric4Value: "92%",
    completedDealTitle: "Enterprise Software Buyout",
    completedDealDescription: "£3.2B acquisition of cybersecurity software company",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Cloud Infrastructure Deal",
    inProgressDealDescription: "£2.8B investment in cloud infrastructure platform",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "BMO Capital Markets",
    headquarters: "Toronto",
    ceo: "Dan Barclay",
    totalDeals: 342,
    totalValue: "£2,145.80 B",
    avgDealSize: "£6.27 B",
    firmType: "Service Provider",
    website: "bmocm.com",
    founded: "1817",
    employees: "45,000+",
    aum: "N/A",
    companySummary: "BMO Capital Markets is a leading, full-service financial services provider. We offer corporate and investment banking, treasury management, as well as research and advisory services to corporations, governments and institutional investors globally. BMO Capital Markets is a member of BMO Financial Group, one of the largest diversified financial services providers in North America.",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£2,145.80B",
    metric2Label: "M&A Deals Completed",
    metric2Value: "342",
    metric3Label: "Canadian M&A Ranking",
    metric3Value: "#3",
    metric4Label: "Client Satisfaction",
    metric4Value: "94%",
    completedDealTitle: "Energy Sector M&A",
    completedDealDescription: "£12.4B advisory on major energy sector acquisition",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Mining Industry Deal",
    inProgressDealDescription: "£8.9B mining sector transaction advisory",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "BNP Paribas",
    headquarters: "Paris",
    ceo: "Jean-Laurent Bonnafé",
    totalDeals: 567,
    totalValue: "£4,892.30 B",
    avgDealSize: "£8.63 B",
    firmType: "Service Provider",
    website: "bnpparibas.com",
    founded: "1848",
    employees: "190,000+",
    aum: "N/A",
    companySummary: "BNP Paribas is a leading bank in Europe with an international reach. It has a presence in 65 countries, with more than 190,000 employees, including more than 148,000 in Europe. The Group has key positions in its three main activities: Domestic Markets and International Financial Services and Corporate & Institutional Banking.",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£4,892.30B",
    metric2Label: "European M&A Deals",
    metric2Value: "567",
    metric3Label: "European Banking Ranking",
    metric3Value: "#4",
    metric4Label: "ESG Advisory Score",
    metric4Value: "96%",
    completedDealTitle: "European Infrastructure",
    completedDealDescription: "£15.7B European infrastructure financing advisory",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Sustainable Finance Deal",
    inProgressDealDescription: "£11.2B green bond issuance advisory",
    inProgressDealDate: "Expected Q2 2025"
  },
  {
    firmName: "Piper Sandler",
    headquarters: "Minneapolis",
    ceo: "Chad Abraham",
    totalDeals: 298,
    totalValue: "£1,234.50 B",
    avgDealSize: "£4.14 B",
    firmType: "Service Provider",
    website: "pipersandler.com",
    founded: "1895",
    employees: "1,700+",
    aum: "N/A",
    companySummary: "Piper Sandler Companies is a leading investment bank and institutional securities firm dedicated to helping clients Realize the Power of Partnership. Securities brokerage and investment banking services are offered through Piper Sandler & Co., member SIPC and NYSE.",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£1,234.50B",
    metric2Label: "Mid-Market Deals",
    metric2Value: "298",
    metric3Label: "Healthcare Banking Ranking",
    metric3Value: "#5",
    metric4Label: "Mid-Market Success Rate",
    metric4Value: "91%",
    completedDealTitle: "Healthcare M&A",
    completedDealDescription: "£4.8B healthcare sector consolidation advisory",
    completedDealDate: "Q4 2024",
    inProgressDealTitle: "Technology IPO",
    inProgressDealDescription: "£2.1B technology company IPO underwriting",
    inProgressDealDate: "Expected Q1 2025"
  },
  {
    firmName: "Societe Generale",
    headquarters: "Paris",
    ceo: "Frédéric Oudéa",
    totalDeals: 445,
    totalValue: "£3,567.90 B",
    avgDealSize: "£8.02 B",
    firmType: "Service Provider",
    website: "societegenerale.com",
    founded: "1864",
    employees: "131,000+",
    aum: "N/A",
    companySummary: "Societe Generale is one of Europe's leading financial services groups. Based in Paris and present in 61 countries, the Group has 131,000 employees. Societe Generale serves 25 million clients worldwide with three complementary core businesses: French Retail Banking, International Retail Banking & Financial Services and Corporate & Investment Banking.",
    metric1Label: "Total Deal Value (2024)",
    metric1Value: "£3,567.90B",
    metric2Label: "International Deals",
    metric2Value: "445",
    metric3Label: "French Banking Ranking",
    metric3Value: "#3",
    metric4Label: "Cross-Border Success",
    metric4Value: "93%",
    completedDealTitle: "Cross-Border M&A",
    completedDealDescription: "£18.3B international acquisition advisory",
    completedDealDate: "Q3 2024",
    inProgressDealTitle: "Structured Finance Deal",
    inProgressDealDescription: "£13.5B structured finance arrangement",
    inProgressDealDate: "Expected Q2 2025"
  }
];

export async function migrateFirmsData() {
  console.log("Starting firms data migration...");
  
  try {
    for (const firmData of staticFirmsData) {
      console.log(`Migrating data for ${firmData.firmName}...`);
      
      // Check if firm already exists
      const existing = await db.select().from(firmsData).where(eq(firmsData.firmName, firmData.firmName)).limit(1);
      
      if (existing.length === 0) {
        await db.insert(firmsData).values(firmData);
        console.log(`✓ Created ${firmData.firmName}`);
      } else {
        console.log(`- ${firmData.firmName} already exists, skipping`);
      }
    }
    
    console.log("Firms data migration completed successfully!");
  } catch (error) {
    console.error("Error during migration:", error);
    throw error;
  }
}

// Run migration if called directly
migrateFirmsData()
  .then(() => {
    console.log("Migration completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Migration failed:", error);
    process.exit(1);
  });